# Generated by Django 4.2.21 on 2025-05-29 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('asset', '자산'), ('liability', '부채'), ('equity', '자본'), ('revenue', '수익'), ('expense', '비용')], max_length=20, verbose_name='구분')),
                ('name', models.CharField(max_length=100, verbose_name='계정명')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리들',
                'db_table': 'categories',
                'ordering': ['type', 'name'],
            },
        ),
    ]
