# Generated by Django 4.2.21 on 2025-05-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_category'),
    ]

    operations = [
    ]
